// Generated by Dokter Website

const DB_NAME = "Database Rumah Aroma";
const SESSION_EXPIRY_SEC = 28800; // Sesi aktif 8 Jam
const MAX_LOGIN_ATTEMPTS = 5;
const LOCK_TIMEOUT_MS = 10000; // Timeout lock spreadsheet 10 detik
const PUBLIC_STORE_TOKEN = "PUBLIC_STORE_TOKEN_SECURE_2026";
const TELEGRAM_TOKEN = "8585644069:AAGb36ajHKyPxt7JeH1x5ckTZBcGB3vZGtk";
const TELEGRAM_CHAT_ID = "-1002736637608";

function doGet(e) {
  return HtmlService.createTemplateFromFile('Index')
    .evaluate()
    .setTitle('Rumah Aroma Indonesia - Premium Custom Perfume')
    .addMetaTag('viewport', 'width=device-width, initial-scale=1')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}

function setupDatabase() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  
  const sheets = {
    "Aroma": ["AromaID", "NamaAroma", "BrandReferensi", "KategoriAroma", "Deskripsi", "HargaDasar", "Status"],
    "Konsentrasi": ["KonsentrasiID", "NamaKonsentrasi", "Persentase", "FaktorHarga", "Ketahanan"],
    "Volume": ["VolumeID", "NamaVolume", "Kategori", "HargaDasar"],
    "Botol": ["BotolID", "NamaBotol", "VolumeID", "BiayaTambahan", "Gambar", "Status"],
    "KuisPertanyaan": ["PertanyaanID", "Pertanyaan", "Urutan"],
    "KuisJawaban": ["JawabanID", "PertanyaanID", "Jawaban", "AromaID"],
    "Pelanggan": ["PelangganID", "Nama", "WhatsApp", "Alamat", "TanggalDaftar"],
    "Pesanan": ["OrderID", "TanggalOrder", "PelangganID", "AromaID", "KonsentrasiID", "VolumeID", "BotolID", "HargaProduk", "MetodePembayaran", "StatusPesanan", "TotalBayar"],
    "Pembayaran": ["PembayaranID", "OrderID", "MetodePembayaran", "Nominal", "StatusPembayaran", "TanggalBayar"],
    "Users": ["Username", "PasswordHash", "Fullname", "Role"],
    "AuditLog": ["Timestamp", "Username", "Action", "Detail"]
  };

  for (let sheetName in sheets) {
    let sheet = ss.getSheetByName(sheetName);
    if (!sheet) {
      sheet = ss.insertSheet(sheetName);
      sheet.appendRow(sheets[sheetName]);
    }
  }

  const userSheet = ss.getSheetByName("Users");
  if (userSheet.getLastRow() === 1) {
    userSheet.appendRow(["admin", hashPassword("Admin@2026"), "Super Admin", "Admin"]);
  }

  populateDefaultMasters(ss);
  return { success: true, message: "Database siap digunakan!" };
}

function populateDefaultMasters(ss) {
  const aromaSheet = ss.getSheetByName("Aroma");
  if (aromaSheet.getLastRow() === 1) {
    aromaSheet.appendRow(["ARM-001", "Baccarat Rouge 540", "MFK", "Sweet", "Aroma mewah elegan dengan sentuhan saffron hangat.", 50000, "Aktif"]);
    aromaSheet.appendRow(["ARM-002", "Aventus", "Creed", "Fresh", "Maskulin, segar, dan berwibawa didominasi kesegaran nanas.", 60000, "Aktif"]);
    aromaSheet.appendRow(["ARM-003", "Black Opium", "YSL", "Sweet", "Manis dan adiktif perpaduan kopi hangat dan vanilla.", 45000, "Aktif"]);
    aromaSheet.appendRow(["ARM-004", "Sauvage", "Dior", "Fresh", "Segar dan spicy mewah, cocok untuk aktivitas kasual.", 55000, "Aktif"]);
    aromaSheet.appendRow(["ARM-005", "English Pear & Freesia", "Jo Malone", "Floral", "Ringan, segar, floral romantis dan elegan.", 40000, "Aktif"]);
  }

  const konsentrasiSheet = ss.getSheetByName("Konsentrasi");
  if (konsentrasiSheet.getLastRow() === 1) {
    konsentrasiSheet.appendRow(["KON-001", "Eau de Toilette (EDT)", 10, 1.0, "4-6 Jam"]);
    konsentrasiSheet.appendRow(["KON-002", "Eau de Parfum (EDP)", 20, 1.5, "8-12 Jam"]);
    konsentrasiSheet.appendRow(["KON-003", "Extrait de Parfum", 35, 2.2, "12-24 Jam"]);
  }

  const volumeSheet = ss.getSheetByName("Volume");
  if (volumeSheet.getLastRow() === 1) {
    volumeSheet.appendRow(["VOL-001", "10ml", "Discovery", 20000]);
    volumeSheet.appendRow(["VOL-002", "30ml", "Beginner", 50000]);
    volumeSheet.appendRow(["VOL-003", "50ml", "Expert", 80000]);
  }

  const botolSheet = ss.getSheetByName("Botol");
  if (botolSheet.getLastRow() === 1) {
    botolSheet.appendRow(["BTL-001", "Kaca Bening Roll-on", "VOL-001", 0, "", "Aktif"]);
    botolSheet.appendRow(["BTL-002", "Travel Size Spray", "VOL-001", 3000, "", "Aktif"]);
    botolSheet.appendRow(["BTL-003", "Kaca Spray Standard", "VOL-002", 5000, "", "Aktif"]);
    botolSheet.appendRow(["BTL-004", "Matte Black Premium", "VOL-003", 15000, "", "Aktif"]);
    botolSheet.appendRow(["BTL-005", "Crystal Clear Premium", "VOL-003", 12000, "", "Aktif"]);
  }

  const qSheet = ss.getSheetByName("KuisPertanyaan");
  if (qSheet.getLastRow() === 1) {
    qSheet.appendRow(["Q-001", "Bagaimana Anda ingin dideskripsikan oleh orang di sekitar Anda?", 1]);
    qSheet.appendRow(["Q-002", "Aktivitas utama saat menggunakan parfum ini?", 2]);
    qSheet.appendRow(["Q-003", "Vibe aroma alam mana yang paling Anda sukai?", 3]);
  }

  const aSheet = ss.getSheetByName("KuisJawaban");
  if (aSheet.getLastRow() === 1) {
    aSheet.appendRow(["A-001", "Q-001", "Manis, hangat, & memikat", "ARM-001"]);
    aSheet.appendRow(["A-002", "Q-001", "Segar, energik, & berwibawa", "ARM-002"]);
    aSheet.appendRow(["A-003", "Q-001", "Lembut, romantis, & anggun", "ARM-005"]);
    aSheet.appendRow(["A-004", "Q-002", "Acara formal / Pertemuan penting malam hari", "ARM-003"]);
    aSheet.appendRow(["A-005", "Q-002", "Kasual, olahraga / Aktivitas harian luar ruangan", "ARM-004"]);
    aSheet.appendRow(["A-006", "Q-003", "Kopi hangat & toko kue vanili", "ARM-003"]);
    aSheet.appendRow(["A-007", "Q-003", "Kebun buah tropis yang segar setelah hujan", "ARM-002"]);
    aSheet.appendRow(["A-008", "Q-003", "Taman mawar dan freesia mekar di pagi hari", "ARM-005"]);
  }
}

function hashPassword(password) {
  const digest = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, password, Utilities.Charset.UTF_8);
  let hexString = '';
  for (let i = 0; i < digest.length; i++) {
    let byteVal = digest[i];
    if (byteVal < 0) byteVal += 256;
    let byteString = byteVal.toString(16);
    if (byteString.length == 1) byteString = '0' + byteString;
    hexString += byteString;
  }
  return hexString;
}

function loginUser(username, password) {
  const cleanUsername = sanitizeInput(username, 50);
  if (checkLoginRateLimit(cleanUsername)) {
    return { success: false, message: "Terlalu banyak percobaan gagal. Akun dikunci sementara 15 menit." };
  }

  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName("Users");
  const data = sheet.getDataRange().getValues();
  const passHash = hashPassword(password);

  for (let i = 1; i < data.length; i++) {
    if (data[i][0] === cleanUsername && data[i][1] === passHash) {
      clearLoginFailures(cleanUsername);
      const token = generateSessionToken(cleanUsername);
      logAction(cleanUsername, "LOGIN", "Berhasil login ke Dashboard Admin");
      return {
        success: true,
        user: { username: data[i][0], fullname: data[i][2], role: data[i][3] },
        token: token
      };
    }
  }

  recordLoginFailure(cleanUsername);
  return { success: false, message: "Username atau password salah." };
}

function generateSessionToken(username) {
  const token = Utilities.getUuid();
  const cache = CacheService.getScriptCache();
  cache.put(token, username, SESSION_EXPIRY_SEC);
  return token;
}

function validateSession(token) {
  if (token === PUBLIC_STORE_TOKEN) {
    return { valid: true, username: "public_customer", role: "Public" };
  }
  if (!token) return { valid: false, message: "Sesi tidak valid / Token kosong" };
  const cache = CacheService.getScriptCache();
  const username = cache.get(token);
  if (!username) return { valid: false, message: "Sesi kedaluwarsa. Silakan login ulang." };
  cache.put(token, username, SESSION_EXPIRY_SEC);
  return { valid: true, username: username };
}

function destroySession(token) {
  const cache = CacheService.getScriptCache();
  cache.remove(token);
  return { success: true };
}

function checkLoginRateLimit(username) {
  const cache = CacheService.getScriptCache();
  const key = "lock_" + username;
  return cache.get(key) !== null;
}

function recordLoginFailure(username) {
  const cache = CacheService.getScriptCache();
  const keyCounter = "fail_cnt_" + username;
  let currentCount = parseInt(cache.get(keyCounter) || "0") + 1;
  cache.put(keyCounter, currentCount.toString(), 900);

  if (currentCount >= MAX_LOGIN_ATTEMPTS) {
    const keyLock = "lock_" + username;
    cache.put(keyLock, "locked", 900);
    cache.remove(keyCounter);
  }
}

function clearLoginFailures(username) {
  const cache = CacheService.getScriptCache();
  cache.remove("fail_cnt_" + username);
  cache.remove("lock_" + username);
}

function logAction(username, action, detail) {
  try {
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName("AuditLog");
    sheet.appendRow([new Date(), username, action, detail]);
  } catch (e) {
    Logger.log("Gagal menulis audit log: " + e.toString());
  }
}

function getPublicData(token) {
  const session = validateSession(token);
  if (!session.valid) return { success: false, message: session.message };

  const ss = SpreadsheetApp.getActiveSpreadsheet();
  
  const aromaData = ss.getSheetByName("Aroma").getDataRange().getValues();
  const aroma = aromaData.slice(1).map(r => ({
    id: r[0], nama: r[1], brand: r[2], kategori: r[3], deskripsi: r[4], hargaDasar: Number(r[5]), status: r[6]
  }));

  const konsenData = ss.getSheetByName("Konsentrasi").getDataRange().getValues();
  const konsentrasi = konsenData.slice(1).map(r => ({
    id: r[0], nama: r[1], persentase: Number(r[2]), faktorHarga: Number(r[3]), ketahanan: r[4]
  }));

  const volData = ss.getSheetByName("Volume").getDataRange().getValues();
  const volume = volData.slice(1).map(r => ({
    id: r[0], nama: r[1], kategori: r[2], hargaDasar: Number(r[3])
  }));

  const botolData = ss.getSheetByName("Botol").getDataRange().getValues();
  const botol = botolData.slice(1).map(r => ({
    id: r[0], nama: r[1], volId: r[2], biayaTambahan: Number(r[3]), gambar: r[4], status: r[5]
  }));

  const kuisQ = ss.getSheetByName("KuisPertanyaan").getDataRange().getValues();
  const kuisPertanyaan = kuisQ.slice(1).map(r => ({
    id: r[0], teks: r[1], urutan: Number(r[2])
  })).sort((a,b) => a.urutan - b.urutan);

  const kuisA = ss.getSheetByName("KuisJawaban").getDataRange().getValues();
  const kuisJawaban = kuisA.slice(1).map(r => ({
    id: r[0], qId: r[1], teks: r[2], aromaId: r[3]
  }));

  return {
    success: true,
    data: { aroma, konsentrasi, volume, botol, kuisPertanyaan, kuisJawaban }
  };
}

function createOrder(token, orderPayload) {
  const session = validateSession(token);
  if (!session.valid) return { success: false, message: session.message };

  const lock = LockService.getScriptLock();
  try {
    if (!lock.tryLock(LOCK_TIMEOUT_MS)) {
      return { success: false, message: "Sistem sedang sibuk. Silakan coba kembali." };
    }

    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const custSheet = ss.getSheetByName("Pelanggan");
    const orderSheet = ss.getSheetByName("Pesanan");
    const paySheet = ss.getSheetByName("Pembayaran");

    const cleanWA = sanitizeInput(orderPayload.customer.wa, 20);
    const cleanName = sanitizeInput(orderPayload.customer.nama, 100);
    const cleanAddr = sanitizeInput(orderPayload.customer.alamat, 500);

    const custData = custSheet.getDataRange().getValues();
    let custId = "";
    for (let i = 1; i < custData.length; i++) {
      if (custData[i][2] === cleanWA) {
        custId = custData[i][0];
        break;
      }
    }

    if (!custId) {
      custId = "CUST-" + Utilities.getUuid().slice(0, 8).toUpperCase();
      custSheet.appendRow([custId, cleanName, cleanWA, cleanAddr, new Date()]);
    }

    const dateStr = Utilities.formatDate(new Date(), "GMT+7", "yyyyMMdd");
    const randCode = Math.floor(1000 + Math.random() * 9000);
    const orderId = "ORDER-" + dateStr + "-" + randCode;

    const hargaSatuan = (orderPayload.aroma.hargaDasar + orderPayload.volume.hargaDasar) * orderPayload.konsentrasi.faktorHarga + orderPayload.botol.biayaTambahan;
    const totalHarga = hargaSatuan * (orderPayload.quantity || 1);

    orderSheet.appendRow([
      orderId,
      new Date(),
      custId,
      orderPayload.aroma.id,
      orderPayload.konsentrasi.id,
      orderPayload.volume.id,
      orderPayload.botol.id,
      hargaSatuan,
      orderPayload.payment,
      "Menunggu Pembayaran",
      totalHarga
    ]);

    const payId = "PAY-" + Utilities.getUuid().slice(0, 8).toUpperCase();
    paySheet.appendRow([
      payId,
      orderId,
      orderPayload.payment,
      totalHarga,
      "Pending",
      ""
    ]);

    sendTelegramNotification(orderId, orderPayload, cleanName, cleanWA, cleanAddr, totalHarga);

    return { success: true, orderId: orderId };
  } catch (err) {
    return { success: false, message: "Kesalahan server: " + err.toString() };
  } finally {
    lock.releaseLock();
  }
}

function sendTelegramNotification(orderId, orderPayload, custName, custWA, custAddr, totalHarga) {
  const url = "https://api.telegram.org/bot" + TELEGRAM_TOKEN + "/sendMessage";

  let message = "<b>⚜️ LAPORAN PESANAN MASUK - RUMAH AROMA ⚜️</b>\n";
  message += "━━━━━━━━━━━━━━━━━━━━━\n";
  message += "<b>ID Pesanan :</b> <code>" + orderId + "</code>\n";
  message += "<b>Waktu :</b> " + safeDateFormat(new Date()) + " WIB\n\n";

  message += "<b>👤 DATA PELANGGAN :</b>\n";
  message += "• <b>Nama :</b> " + custName + "\n";
  message += "• <b>WhatsApp :</b> " + custWA + "\n";
  message += "• <b>Alamat :</b> " + custAddr + "\n\n";

  message += "<b>🧪 DETAIL PARFUM KUSTOM :</b>\n";
  message += "• <b>Aroma :</b> " + orderPayload.aroma.nama + " (Ref: " + orderPayload.aroma.brand + ")\n";
  message += "• <b>Konsentrasi :</b> " + orderPayload.konsentrasi.nama + "\n";
  message += "• <b>Volume :</b> " + orderPayload.volume.nama + "\n";
  message += "• <b>Desain Botol :</b> " + orderPayload.botol.nama + "\n";
  message += "• <b>Jumlah Pesanan :</b> " + orderPayload.quantity + " Botol\n\n";

  message += "<b>💳 INFORMASI PEMBAYARAN :</b>\n";
  message += "• <b>Metode :</b> " + orderPayload.payment + "\n";
  message += "• <b>Total Bayar :</b> <b>Rp " + Number(totalHarga).toLocaleString('id-ID') + "</b>\n";
  message += "━━━━━━━━━━━━━━━━━━━━━\n";
  message += "<i>Mohon periksa mutasi bank / QRIS Anda untuk validasi.</i>";

  const options = {
    "method": "post",
    "contentType": "application/json",
    "payload": JSON.stringify({
      "chat_id": TELEGRAM_CHAT_ID,
      "text": message,
      "parse_mode": "HTML"
    }),
    "muteHttpExceptions": true
  };

  try {
    UrlFetchApp.fetch(url, options);
  } catch (e) {
    Logger.log("Gagal mengirim Telegram: " + e.toString());
  }
}

function getAdminDashboard(token) {
  const session = validateSession(token);
  if (!session.valid) return { success: false, message: session.message, sessionExpired: true };

  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const orderData = ss.getSheetByName("Pesanan").getDataRange().getValues().slice(1);
  const aromaCount = ss.getSheetByName("Aroma").getLastRow() - 1;
  const custCount = ss.getSheetByName("Pelanggan").getLastRow() - 1;

  let omset = 0;
  orderData.forEach(r => {
    if (["Diproses", "Dikirim", "Selesai"].indexOf(r[9]) > -1) {
      omset += Number(r[10] || 0);
    }
  });

  const parsedOrders = orderData.map(r => ({
    orderId: r[0],
    tanggal: safeDateFormat(r[1]),
    pelangganNama: getCustomerName(ss, r[2]),
    aromaNama: getAromaName(ss, r[3]),
    totalBayar: Number(r[10]),
    status: r[9]
  })).reverse();

  return {
    success: true,
    data: {
      pesanan: parsedOrders,
      totalAroma: aromaCount,
      totalPelanggan: custCount,
      totalOmset: omset
    }
  };
}

function getAromaList(token) {
  const session = validateSession(token);
  if (!session.valid) return { success: false, message: session.message, sessionExpired: true };

  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const list = ss.getSheetByName("Aroma").getDataRange().getValues().slice(1).map(r => ({
    id: r[0], nama: r[1], brand: r[2], kategori: r[3], deskripsi: r[4], hargaDasar: Number(r[5]), status: r[6]
  }));

  return { success: true, data: list };
}

function saveAromaData(token, payload) {
  const session = validateSession(token);
  if (!session.valid) return { success: false, message: session.message, sessionExpired: true };

  const lock = LockService.getScriptLock();
  try {
    if (!lock.tryLock(LOCK_TIMEOUT_MS)) return { success: false, message: "Database dikunci oleh proses lain." };

    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName("Aroma");
    const data = sheet.getDataRange().getValues();
    let rowIdx = -1;

    const cleanNama = sanitizeInput(payload.nama, 100);
    const cleanBrand = sanitizeInput(payload.brand, 100);
    const cleanDesc = sanitizeInput(payload.deskripsi, 500);

    if (payload.id) {
      for (let i = 1; i < data.length; i++) {
        if (data[i][0] === payload.id) {
          rowIdx = i + 1;
          break;
        }
      }
    }

    if (rowIdx > -1) {
      sheet.getRange(rowIdx, 2, 1, 6).setValues([[
        cleanNama,
        cleanBrand,
        payload.kategori,
        cleanDesc,
        payload.hargaDasar,
        payload.status
      ]]);
      logAction(session.username, "UPDATE_AROMA", "Mengubah aroma " + payload.id);
    } else {
      const newId = "ARM-" + Math.floor(1000 + Math.random() * 9000);
      sheet.appendRow([
        newId,
        cleanNama,
        cleanBrand,
        payload.kategori,
        cleanDesc,
        payload.hargaDasar,
        payload.status
      ]);
      logAction(session.username, "CREATE_AROMA", "Membuat master aroma baru " + newId);
    }

    return { success: true };
  } catch(e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}

function getCustomerName(ss, custId) {
  const data = ss.getSheetByName("Pelanggan").getDataRange().getValues();
  for (let i = 1; i < data.length; i++) {
    if (data[i][0] === custId) return data[i][1];
  }
  return "Pelanggan Umum";
}

function getAromaName(ss, aromaId) {
  const data = ss.getSheetByName("Aroma").getDataRange().getValues();
  for (let i = 1; i < data.length; i++) {
    if (data[i][0] === aromaId) return data[i][1];
  }
  return "-";
}

function sanitizeInput(val, maxLength) {
  if (!val) return "";
  let clean = String(val).replace(/<[^>]*>/g, '').trim();
  if (clean.length > maxLength) {
    clean = clean.slice(0, maxLength);
  }
  return clean;
}

function safeDateFormat(val) {
  if (!val) return "-";
  if (val instanceof Date) {
    return Utilities.formatDate(val, "GMT+7", "yyyy-MM-dd HH:mm");
  }
  return String(val);
}
